{{ $ca := genCA "pso-db-ca" 36500 }}
{{- $altNames := list "localhost" ( printf "*.pso-db.%s" .Release.Namespace ) -}}
{{ $node := genSignedCert "node" nil $altNames 36500 $ca }}
{{ $client := genSignedCert "root" nil nil 36500 $ca }}

apiVersion: v1
kind: Secret
metadata:
    name: pso-cockroach-node-certs
    namespace: {{ .Release.Namespace }}
    labels:
        app: {{ template "pure-csi.name" . }}
        chart: {{ template "pure-csi.chart" . }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
data:
    ca.crt: {{ b64enc $ca.Cert }}
    node.crt: {{ b64enc $node.Cert }}
    node.key: {{ b64enc $node.Key }}
        {{/* v- Temporary for testing -v */}}
    client.root.crt: {{ b64enc $client.Cert }}
    client.root.key: {{ b64enc $client.Key }}
---
apiVersion: v1
kind: Secret
metadata:
    name: pso-cockroach-client-certs
    namespace: {{ .Release.Namespace }}
    labels:
        app: {{ template "pure-csi.name" . }}
        chart: {{ template "pure-csi.chart" . }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
data:
    ca.crt: {{ b64enc $ca.Cert }}
    client.root.crt: {{ b64enc $client.Cert }}
    client.root.key: {{ b64enc $client.Key }}
