apiVersion: v1
kind: Secret
metadata:
  name: pure-delete-job-token
  annotations:
    helm.sh/hook: pre-delete # Run before delete because we still need the role created by the helm chart
    helm.sh/hook-delete-policy: hook-succeeded
    kubernetes.io/service-account.name: pure
type: kubernetes.io/service-account-token
---
apiVersion: batch/v1
kind: Job
metadata:
  name: secret-cleanup-job
  annotations:
    helm.sh/hook: pre-delete # Run before delete because we still need the role created by the helm chart
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.clusterrolebinding.serviceAccount.name }}
      automountServiceAccountToken: true  # Mounts to /var/run/secrets/kubernetes.io/serviceaccount/token
      restartPolicy: Never
      containers:
        - name: pre-delete
          image: curlimages/curl:7.70.0
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: pure-delete-job-token
                  key: token
          command:
            - curl
            - -v
            - -XDELETE
            - --cacert
            - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - -H
            - "Authorization: Bearer $(TOKEN)"
            - https://kubernetes.default.svc/api/v1/namespaces/$(NAMESPACE)/secrets/pure-provisioner-secret
