kind: Role
apiVersion: {{ template "rbac.apiVersion" . }}
metadata:
  name: pso-db-runner
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pure-csi.labels" . | indent 4 }}
  annotations:
    "helm.sh/resource-policy": keep  # THIS IS IMPORTANT: it's what allows the cockroach operator to clean itself up
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs: ["create", "list", "watch", "delete", "get", "update"]
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs: ["create", "list", "watch", "delete", "get", "update"]
- apiGroups:
  - batch
  resources:
  - jobs
  verbs: ["create", "list", "watch", "delete", "get", "update"]
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - pso-db-deployer
  - pso-cockroach-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - pso.purestorage.com
  resources:
  - '*'
  verbs: ["create", "list", "watch", "delete", "get", "update"]

# Post-delete RBAC cleanup stuff: whatever MUST remain around after helm delete should be added here so our pods can
# clean it up right before cleaning up themselves

# Enable listing of all necessary RBAC resources
- apiGroups:
    - ""  # ServiceAccounts
    - rbac.authorization.k8s.io  # Roles and RoleBindings
  resources:
    - serviceaccounts
    - roles
    - rolebindings
  verbs: ["list"]

# Updating of ServiceAccounts
- apiGroups:
    - ""
  resources:
    - serviceaccounts
  verbs: ["get", "update"]
  resourceNames:
    - {{ .Values.clusterrolebinding.serviceAccount.name }}
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - roles
  verbs: ["get", "update"]
  resourceNames:
    - pso-db-runner
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - rolebindings
  verbs: ["get", "update"]
  resourceNames:
    - pso-db-role
---

kind: RoleBinding
apiVersion: {{ template "rbac.apiVersion" . }}
metadata:
  name: pso-db-role
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pure-csi.labels" . | indent 4 }}
  annotations:
    "helm.sh/resource-policy": keep  # THIS IS IMPORTANT: it's what allows the cockroach operator to clean itself up
subjects:
- kind: ServiceAccount
  name: {{ .Values.clusterrolebinding.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: pso-db-runner
  apiGroup: rbac.authorization.k8s.io
