apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-pure-storage-attach
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      files:
      - path: /etc/multipath.conf
        mode: 384
        filesystem: root
        contents:
          source: data:,defaults%20%7b%0a%20%20%20%20%20%20%20polling_interval%7d%0adevices%20%7b%0a%20%20device%20%7b%0a%20%20%20%20%20%20%20%20vendor%20%22PURE%22%0a%20%20%20%20%20%20%20%20product%20%22FlashArray%22%0a%20%20%20%20%20%20%20%20fast_io_fail_tmo%2010%0a%20%20%20%20%20%20%20%20path_grouping_policy%20%22group_by_prio%22%0a%20%20%20%20%20%20%20%20failback%20%22immediate%22%0a%20%20%20%20%20%20%20%20prio%20%22alua%22%0a%20%20%20%20%20%20%20%20hardware_handler%20%221%20alua%22%0a%20%20%20%20%20%20%20%20max_sectors_kb%204096%0a%20%20%20%20%7d%0a%7d
          verification: {}
      - path: /etc/udev/rules.d/99-pure-storage.rules
        mode: 420
        filesystem: root
        contents:
          source: data:,%23%20Recommended%20settings%20for%20Pure%20Storage%20FlashArray.%0a%23%20Use%20noop%20scheduler%20for%20high-performance%20solid-state%20storage%20for%20SCSI%20devices%0aACTION%3d%3d%22add%7cchange%22%2c%20KERNEL%3d%3d%22sd%2a%5b%210-9%5d%22%2c%20SUBSYSTEM%3d%3d%22block%22%2c%20ENV%7bID_VENDOR%7d%3d%3d%22PURE%22%2c%20ATTR%7bqueue%2fscheduler%7d%3d%22none%22%0aACTION%3d%3d%22add%7cchange%22%2c%20KERNEL%3d%3d%22dm-%5b0-9%5d%2a%22%2c%20SUBSYSTEM%3d%3d%22block%22%2c%20ENV%7bDM_NAME%7d%3d%3d%223624a937%2a%22%2c%20ATTR%7bqueue%2fscheduler%7d%3d%22none%22%0a%0a%23%20Reduce%20CPU%20overhead%20due%20to%20entropy%20collection%0aACTION%3d%3d%22add%7cchange%22%2c%20KERNEL%3d%3d%22sd%2a%5b%210-9%5d%22%2c%20SUBSYSTEM%3d%3d%22block%22%2c%20ENV%7bID_VENDOR%7d%3d%3d%22PURE%22%2c%20ATTR%7bqueue%2fadd_random%7d%3d%220%22%0aACTION%3d%3d%22add%7cchange%22%2c%20KERNEL%3d%3d%22dm-%5b0-9%5d%2a%22%2c%20SUBSYSTEM%3d%3d%22block%22%2c%20ENV%7bDM_NAME%7d%3d%3d%223624a937%2a%22%2c%20ATTR%7bqueue%2fadd_random%7d%3d%220%22%0a%0a%23%20Spread%20CPU%20load%20by%20redirecting%20completions%20to%20originating%20CPU%0aACTION%3d%3d%22add%7cchange%22%2c%20KERNEL%3d%3d%22sd%2a%5b%210-9%5d%22%2c%20SUBSYSTEM%3d%3d%22block%22%2c%20ENV%7bID_VENDOR%7d%3d%3d%22PURE%22%2c%20ATTR%7bqueue%2frq_affinity%7d%3d%222%22%0aACTION%3d%3d%22add%7cchange%22%2c%20KERNEL%3d%3d%22dm-%5b0-9%5d%2a%22%2c%20SUBSYSTEM%3d%3d%22block%22%2c%20ENV%7bDM_NAME%7d%3d%3d%223624a937%2a%22%2c%20ATTR%7bqueue%2frq_affinity%7d%3d%222%22%0a%0a%23%20Set%20the%20HBA%20timeout%20to%2060%20seconds%0aACTION%3d%3d%22add%7cchange%22%2c%20KERNEL%3d%3d%22sd%2a%5b%210-9%5d%22%2c%20SUBSYSTEM%3d%3d%22block%22%2c%20ENV%7bID_VENDOR%7d%3d%3d%22PURE%22%2c%20ATTR%7bdevice%2ftimeout%7d%3d%2260%22%0a%0a%23%20Set%20maximum%20IO%20size%0aACTION%3d%3d%22add%7cchange%22%2c%20KERNEL%3d%3d%22sd%2a%5b%210-9%5d%22%2c%20SUBSYSTEM%3d%3d%22block%22%2c%20ENV%7bID_VENDOR%7d%3d%3d%22PURE%22%2c%20ATTR%7bqueue%2fmax_sectors_kb%7d%3d%224096%22
          verification: {}
      - path: /etc/udev/rules.d/90-scsi-ua.rules
        mode: 420
        filesystem: root
        contents:
          source: data:,ACTION%3d%3d%22change%22%2c%20SUBSYSTEM%3d%3d%22scsi%22%2c%20ENV%7bSDEV_UA%7d%3d%3d%22CAPACITY_DATA_HAS_CHANGED%22%2c%20TEST%3d%3d%22rescan%22%2c%20ATTR%7brescan%7d%3d%22x%22%0aACTION%3d%3d%22change%22%2c%20SUBSYSTEM%3d%3d%22scsi%22%2c%20ENV%7bSDEV_UA%7d%3d%3d%22REPORTED_LUNS_DATA_HAS_CHANGED%22%2c%20RUN%2b%3d%22scan-scsi-target%20%24env%7bDEVPATH%7d%22
          verification: {}
    systemd:
      units:
        - name: multipathd.service
          enabled: true
        - name: iscsid.service
          enabled: true
