# PSO to PX Tool Spec
apiVersion: v1
kind: ServiceAccount
metadata:
 name: pso2px-tool
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: pso2px-tool
rules:
 - apiGroups: ["*"]
   resources: ["*"]
   verbs: ["*"]
--- 
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: pso2px-tool
subjects:
- kind: ServiceAccount
 name: pso2px-tool
 namespace: default
roleRef:
 kind: ClusterRole
 name: pso2px-tool
 apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
 name: pso2px
 labels:
   app: pso2px
spec:
 containers:
 - name: pso2px
   image: portworx/pso2px:v1.0.0-beta
   imagePullPolicy: Always
   volumeMounts:
   - mountPath: /csi.sock
     name: csi-volume
   - mountPath: /usr/local/pso2px/k8s_backups
     name: backup-path
 volumes:
   - name: csi-volume
     hostPath:
       path: /var/lib/kubelet/plugins/pxd.portworx.com/csi.sock        
   - name: backup-path
     hostPath:
       path: /usr/local/pso2px/k8s_backups
       type: DirectoryOrCreate
 serviceAccount: pso2px-tool
 serviceAccountName: pso2px-tool